### ISSUE TITLE
Extension window disappears after focus returns back to it

### ISSUE THREAD

**Issue by khssnv** [BTE-Trusted-Entity/sporran-extension#1385]
Hi,

When I change focus to the notes app to write down the seed phrase and then return back to click "Next step" button extension window disappears and generates a new seed phrase.

The same happens when I setup account password. I'm switching focus to password manager to generate it, but the window disappears and resets the flow state on focus return again.

**Comment by arty-name** [comment]
Thank you for reporting an issue!

Unfortunately this is expected behavior. This is just what the extension popups do in some browsers: disappear when they lose focus. We investigate the improvements we could make for the flow, but for now we recommend the old school approach of using pen and paper to write down or recover the backup phrase. This approach is also the most secure from remote attacks.

I must also say that we have left the issues section on the GitHub as an oversight. The support channels are [this page](https://support.kilt.io/), as well as the KILT channels on Discord and Telegram. We will be closing the issues section shortly.
